<?php

return [
    'access_request_notification_email' => env(
        'WMS_ACCESS_REQUEST_NOTIFICATION_EMAIL',
        'administracion@maximosl.com'
    ),

    'navigation_sections' => [
        [
            'key' => 'stock',
            'title' => 'Stock',
            'summary' => 'Visibilidad operativa por articulo, palet y estructura fisica del almacen.',
            'minimum_role' => 'almacen',
            'children' => [
                [
                    'key' => 'stock',
                    'route' => 'stock.index',
                    'path' => '/stock',
                    'title' => 'Stock actual',
                    'summary' => 'Vista operativa por articulo con cantidad total, palets completos y picos.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Visibilidad',
                    'status' => 'ready',
                    'next_step' => 'Conectar movimientos, ubicaciones reales y trazabilidad completa.',
                    'active_patterns' => ['stock.index'],
                ],
                [
                    'key' => 'items',
                    'route' => 'items.index',
                    'path' => '/articulos',
                    'title' => 'Articulos',
                    'summary' => 'Maestro de producto por cliente con paletizado estandar.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Maestro',
                    'status' => 'ready',
                    'active_patterns' => ['items.*'],
                ],
                [
                    'key' => 'pallets',
                    'route' => 'modules.pallets',
                    'path' => '/palets',
                    'title' => 'Palets',
                    'summary' => 'Control futuro de palets individuales, trazabilidad y detalle operativo.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Operacion',
                    'status' => 'placeholder',
                    'next_step' => 'Definir modelo de palet y cantidad real por unidad logistica.',
                    'active_patterns' => ['modules.pallets'],
                ],
                [
                    'key' => 'locations',
                    'route' => 'modules.locations',
                    'path' => '/ubicaciones',
                    'title' => 'Ubicaciones',
                    'summary' => 'Mapa futuro de ubicaciones, calles y zonas operativas.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Layout',
                    'status' => 'placeholder',
                    'next_step' => 'Diseñar ubicaciones fisicas y reglas de asignacion.',
                    'active_patterns' => ['modules.locations'],
                ],
            ],
        ],
        [
            'key' => 'operations',
            'title' => 'Operaciones',
            'summary' => 'Entrada, salida y solicitudes operativas del circuito WMS.',
            'minimum_role' => 'cliente',
            'children' => [
                [
                    'key' => 'solicitudes',
                    'route' => 'modules.requests',
                    'path' => '/solicitudes',
                    'title' => 'Solicitudes de mercancia',
                    'summary' => 'Alta y seguimiento de necesidades operativas y expediciones.',
                    'minimum_role' => 'cliente',
                    'tag' => 'Operacion',
                    'status' => 'placeholder',
                    'next_step' => 'Diseñar flujo de solicitud por cliente y validacion operativa.',
                    'active_patterns' => ['modules.requests'],
                ],
                [
                    'key' => 'entradas',
                    'route' => 'modules.inbound',
                    'path' => '/entradas',
                    'title' => 'Entradas',
                    'summary' => 'Recepcion de mercancia, control documental y puesta en ubicacion.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Almacen',
                    'status' => 'placeholder',
                    'next_step' => 'Definir recepcion, estado de palets y validaciones.',
                    'active_patterns' => ['modules.inbound'],
                ],
                [
                    'key' => 'salidas',
                    'route' => 'modules.outbound',
                    'path' => '/salidas',
                    'title' => 'Salidas',
                    'summary' => 'Preparacion, picking, expedicion y control de salidas.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Almacen',
                    'status' => 'placeholder',
                    'next_step' => 'Diseñar flujo de pedido, reserva y expedicion.',
                    'active_patterns' => ['modules.outbound'],
                ],
            ],
        ],
        [
            'key' => 'management',
            'title' => 'Gestion',
            'summary' => 'Configuracion de clientes, almacenes y parametros base.',
            'minimum_role' => 'administracion',
            'children' => [
                [
                    'key' => 'clientes',
                    'route' => 'modules.clients',
                    'path' => '/clientes',
                    'title' => 'Clientes',
                    'summary' => 'Gestion futura de cuentas cliente y parametros comerciales.',
                    'minimum_role' => 'administracion',
                    'tag' => 'Gestion',
                    'status' => 'placeholder',
                    'next_step' => 'Evolucionar el maestro de clientes y su relacion con usuarios.',
                    'active_patterns' => ['modules.clients'],
                ],
                [
                    'key' => 'almacenes',
                    'route' => 'modules.warehouses',
                    'path' => '/almacenes',
                    'title' => 'Almacenes',
                    'summary' => 'Configuracion de almacenes, zonas y estructura operativa.',
                    'minimum_role' => 'administracion',
                    'tag' => 'Gestion',
                    'status' => 'placeholder',
                    'next_step' => 'Modelar almacenes, areas y capacidades.',
                    'active_patterns' => ['modules.warehouses'],
                ],
            ],
        ],
        [
            'key' => 'system',
            'title' => 'Sistema',
            'summary' => 'Control interno de seguridad, auditoria y continuidad.',
            'minimum_role' => 'administracion',
            'children' => [
                [
                    'key' => 'usuarios',
                    'route' => 'modules.users',
                    'path' => '/usuarios',
                    'title' => 'Usuarios y roles',
                    'summary' => 'Jerarquia de accesos y gobierno funcional del sistema.',
                    'minimum_role' => 'superadmin',
                    'tag' => 'Seguridad',
                    'status' => 'placeholder',
                    'next_step' => 'Extender gestion de usuarios y asignacion por cliente.',
                    'active_patterns' => ['modules.users'],
                ],
                [
                    'key' => 'auditoria',
                    'route' => 'modules.audit',
                    'path' => '/auditoria',
                    'title' => 'Auditoria y trazabilidad',
                    'summary' => 'Seguimiento de actividad y eventos clave del WMS.',
                    'minimum_role' => 'administracion',
                    'tag' => 'Control',
                    'status' => 'placeholder',
                    'next_step' => 'Capturar eventos relevantes y trazabilidad completa.',
                    'active_patterns' => ['modules.audit'],
                ],
                [
                    'key' => 'backups',
                    'route' => 'modules.backups',
                    'path' => '/backups',
                    'title' => 'Backups',
                    'summary' => 'Continuidad operativa y supervision de copias de seguridad.',
                    'minimum_role' => 'superadmin',
                    'tag' => 'Infraestructura',
                    'status' => 'placeholder',
                    'next_step' => 'Visualizar estado de copias y alertas criticas.',
                    'active_patterns' => ['modules.backups'],
                ],
            ],
        ],
    ],
];
