<?php

return [
    'access_request_notification_email' => env(
        'WMS_ACCESS_REQUEST_NOTIFICATION_EMAIL',
        'administracion@maximosl.com'
    ),

    'merchandise_requests' => [
        'schedule' => [
            'timezone' => env('APP_TIMEZONE', 'Europe/Madrid'),
            'business_days' => [1, 2, 3, 4, 5],
            'start' => '08:00',
            'end' => '17:00',
            // TODO: Configurar aqui el horario real de empresa y el mensaje final definitivo para pedidos.
        ],
    ],

    'navigation_sections' => [
        [
            'key' => 'stock',
            'title' => 'Stock',
            'summary' => 'Visibilidad operativa por articulo, palet y estructura fisica del almacen.',
            'minimum_role' => 'almacen',
            'children' => [
                [
                    'key' => 'stock',
                    'route' => 'stock.index',
                    'path' => '/stock',
                    'title' => 'Stock actual',
                    'summary' => 'Vista operativa por articulo con cantidad total, palets completos y picos.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Visibilidad',
                    'status' => 'ready',
                    'next_step' => 'Conectar movimientos, ubicaciones reales y trazabilidad completa.',
                    'active_patterns' => ['stock.index'],
                ],
                [
                    'key' => 'items',
                    'route' => 'items.index',
                    'path' => '/articulos',
                    'title' => 'Articulos',
                    'summary' => 'Maestro de producto por cliente con paletizado estandar.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Maestro',
                    'status' => 'ready',
                    'active_patterns' => ['items.*'],
                ],
                [
                    'key' => 'pallets',
                    'route' => 'modules.pallets',
                    'path' => '/palets',
                    'title' => 'Palets',
                    'summary' => 'Control futuro de palets individuales, trazabilidad y detalle operativo.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Operacion',
                    'status' => 'placeholder',
                    'next_step' => 'Definir modelo de palet y cantidad real por unidad logistica.',
                    'active_patterns' => ['modules.pallets'],
                ],
                [
                    'key' => 'locations',
                    'route' => 'locations.index',
                    'path' => '/ubicaciones',
                    'title' => 'Ubicaciones',
                    'summary' => 'Mapa operativo de ubicaciones, zonas y referencias visibles en stock.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Layout',
                    'status' => 'ready',
                    'next_step' => 'Conectar asignacion de stock y reglas de ubicacion automatica.',
                    'active_patterns' => ['locations.*'],
                ],
            ],
        ],
        [
            'key' => 'operations',
            'title' => 'Operaciones',
            'summary' => 'Entrada, salida y solicitudes operativas del circuito WMS.',
            'minimum_role' => 'cliente',
            'children' => [
                [
                    'key' => 'bookings',
                    'route' => 'bookings.index',
                    'path' => '/bookings',
                    'title' => 'Bookings',
                    'summary' => 'Solicitud y seguimiento de bookings de entrada y salida por cliente.',
                    'minimum_role' => 'cliente',
                    'tag' => 'Planificacion',
                    'status' => 'ready',
                    'next_step' => 'Sincronizar con Google Workspace Calendar y conectar con operativa diaria.',
                    'active_patterns' => ['bookings.index', 'bookings.create', 'bookings.show', 'bookings.edit', 'bookings.update', 'bookings.store', 'bookings.update-status'],
                ],
                [
                    'key' => 'bookings-calendar',
                    'route' => 'bookings.calendar',
                    'path' => '/bookings/calendario',
                    'title' => 'Calendario de bookings',
                    'summary' => 'Agenda operativa interna de bookings agrupados por fecha.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Calendario',
                    'status' => 'ready',
                    'next_step' => 'Alinear agenda interna con calendario corporativo y capacidad real de muelles.',
                    'active_patterns' => ['bookings.calendar'],
                ],
                [
                    'key' => 'solicitudes',
                    'route' => 'merchandise-requests.index',
                    'path' => '/solicitudes-mercancia',
                    'title' => 'Solicitar mercancia',
                    'summary' => 'Solicitud de pallets por cliente y consulta interna de pedidos recibidos.',
                    'minimum_role' => 'cliente',
                    'tag' => 'Operacion',
                    'status' => 'ready',
                    'next_step' => 'Conectar reglas reales de horario, preparacion y cierre de pedidos.',
                    'active_patterns' => ['merchandise-requests.*'],
                ],
                [
                    'key' => 'entradas',
                    'route' => 'goods-receipts.index',
                    'path' => '/entradas',
                    'title' => 'Entradas',
                    'summary' => 'Recepcion de mercancia, control documental y puesta en ubicacion.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Almacen',
                    'status' => 'ready',
                    'next_step' => 'Conectar OCR/IA para propuesta automatica de entradas y extraccion documental.',
                    'active_patterns' => ['goods-receipts.*'],
                ],
                [
                    'key' => 'salidas',
                    'route' => 'dispatches.index',
                    'path' => '/salidas',
                    'title' => 'Salidas',
                    'summary' => 'Preparacion, picking, expedicion y control de salidas.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Almacen',
                    'status' => 'ready',
                    'next_step' => 'Integrar impacto real sobre stock y expediciones definitivas.',
                    'active_patterns' => ['dispatches.*'],
                ],
                [
                    'key' => 'operaciones-diarias',
                    'route' => 'daily-operations.index',
                    'path' => '/operaciones-diarias',
                    'title' => 'Operaciones diarias',
                    'summary' => 'Control diario de pallets, movimientos y base operativa de facturación.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Operacion',
                    'status' => 'ready',
                    'next_step' => 'Añadir booking, sin booking y reglas finales de facturación FF.',
                    'active_patterns' => ['daily-operations.*'],
                ],
            ],
        ],
        [
            'key' => 'management',
            'title' => 'Gestion',
            'summary' => 'Configuracion de clientes, almacenes y parametros base.',
            'minimum_role' => 'administracion',
            'children' => [
                [
                    'key' => 'clientes',
                    'route' => 'clients.index',
                    'path' => '/clientes',
                    'title' => 'Clientes',
                    'summary' => 'Gestion de clientes, activacion y direccion de entrega.',
                    'minimum_role' => 'administracion',
                    'tag' => 'Gestion',
                    'status' => 'ready',
                    'next_step' => 'Completar datos comerciales y parametros especificos por cliente.',
                    'active_patterns' => ['clients.*'],
                ],
                [
                    'key' => 'almacenes',
                    'route' => 'warehouses.index',
                    'path' => '/almacenes',
                    'title' => 'Almacenes',
                    'summary' => 'Configuracion operativa de almacenes y estructura base.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Gestion',
                    'status' => 'ready',
                    'next_step' => 'Extender capacidades, zonas y reglas por cliente.',
                    'active_patterns' => ['warehouses.*'],
                ],
                [
                    'key' => 'proveedores',
                    'route' => 'suppliers.index',
                    'path' => '/proveedores',
                    'title' => 'Proveedores',
                    'summary' => 'Maestro de proveedores por cliente o ambito global para entradas de mercancia.',
                    'minimum_role' => 'almacen',
                    'tag' => 'Gestion',
                    'status' => 'ready',
                    'next_step' => 'Relacionar condiciones logisticas, documentos y trazabilidad por proveedor.',
                    'active_patterns' => ['suppliers.*'],
                ],
            ],
        ],
        [
            'key' => 'system',
            'title' => 'Sistema',
            'summary' => 'Control interno de seguridad, auditoria y continuidad.',
            'minimum_role' => 'administracion',
            'children' => [
                [
                    'key' => 'usuarios',
                    'route' => 'users.index',
                    'path' => '/usuarios',
                    'title' => 'Usuarios y roles',
                    'summary' => 'Gestion de usuarios, asignacion de cliente y control de roles.',
                    'minimum_role' => 'administracion',
                    'tag' => 'Seguridad',
                    'status' => 'ready',
                    'next_step' => 'Extender altas operativas y flujos de aprobacion de acceso.',
                    'active_patterns' => ['users.*'],
                ],
                [
                    'key' => 'access-requests',
                    'route' => 'access-requests.index',
                    'path' => '/solicitudes-acceso',
                    'title' => 'Solicitudes de acceso',
                    'summary' => 'Revision de altas externas y aprobacion de usuarios cliente.',
                    'minimum_role' => 'administracion',
                    'tag' => 'Seguridad',
                    'status' => 'ready',
                    'next_step' => 'Extender el flujo con indicadores de carga y SLA de revision.',
                    'active_patterns' => ['access-requests.*'],
                ],
                [
                    'key' => 'auditoria',
                    'route' => 'audit.index',
                    'path' => '/auditoria',
                    'title' => 'Auditoria y trazabilidad',
                    'summary' => 'Herramientas de control, trazabilidad y mantenimiento seguro del WMS.',
                    'minimum_role' => 'administracion',
                    'tag' => 'Control',
                    'status' => 'ready',
                    'next_step' => 'Ampliar trazabilidad, retención de datos y purgas avanzadas con política definitiva.',
                    'active_patterns' => ['audit.*'],
                ],
                [
                    'key' => 'backups',
                    'route' => 'modules.backups',
                    'path' => '/backups',
                    'title' => 'Backups',
                    'summary' => 'Continuidad operativa y supervision de copias de seguridad.',
                    'minimum_role' => 'superadmin',
                    'tag' => 'Infraestructura',
                    'status' => 'placeholder',
                    'next_step' => 'Visualizar estado de copias y alertas criticas.',
                    'active_patterns' => ['modules.backups'],
                ],
            ],
        ],
    ],
];
