@extends('layouts.dashboard')

@section('title', 'Analitica | Trazabilidad')
@section('topbar_title', 'Analitica por cliente')

@section('content')
    <x-breadcrumbs :items="[['label' => 'Trazabilidad', 'href' => route('traceability.index'), 'icon' => 'audit'], ['label' => 'Analitica']]" />
    @include('traceability._nav')
    <section class="surface-card item-filter-card compact-card"><form method="GET" class="stock-filters compact-filters filters-compact">
        <label class="auth-field"><span>Cliente *</span><select name="client_id" class="auth-input" required><option value="">Seleccionar</option>@foreach ($clients as $client)<option value="{{ $client->id }}" @selected((int) ($filters['client_id'] ?? 0) === $client->id)>{{ $client->name }}</option>@endforeach</select></label>
        <label class="auth-field"><span>Articulo</span><select name="item_id" class="auth-input"><option value="">Todos</option>@foreach ($items as $item)<option value="{{ $item->id }}" @selected((int) ($filters['item_id'] ?? 0) === $item->id)>{{ $item->sku }} · {{ $item->description }}</option>@endforeach</select></label>
        <label class="auth-field"><span>Categoria</span><select name="category" class="auth-input"><option value="">Todas</option>@foreach ($categories as $value => $label)<option value="{{ $value }}" @selected(($filters['category'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></label>
        <label class="auth-field"><span>Lote</span><input type="text" name="lot" value="{{ $filters['lot'] ?? '' }}" maxlength="100" class="auth-input"></label>
        <label class="auth-field"><span>Almacen</span><select name="warehouse_id" class="auth-input"><option value="">Todos</option>@foreach ($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected((int) ($filters['warehouse_id'] ?? 0) === $warehouse->id)>{{ $warehouse->name }}</option>@endforeach</select></label>
        <label class="auth-field"><span>Desde</span><input type="date" name="date_from" value="{{ $filters['date_from'] }}" class="auth-input"></label><label class="auth-field"><span>Hasta</span><input type="date" name="date_to" value="{{ $filters['date_to'] }}" class="auth-input"></label>
        <div class="stock-filter-actions action-buttons"><button class="button-primary compact-button btn-compact">Analizar</button><a href="{{ route('traceability.analytics.index') }}" class="button-secondary compact-button btn-compact">Limpiar</a></div>
    </form></section>
    @if ($results)
        <section class="traceability-kpi-grid"><article class="surface-card kpi-card kpi-compact"><span>Entradas</span><strong>{{ number_format($results['total_inbound'], 0, ',', '.') }} uds</strong></article><article class="surface-card kpi-card kpi-compact"><span>Salidas</span><strong>{{ number_format($results['total_outbound'], 0, ',', '.') }} uds</strong></article><article class="surface-card kpi-card kpi-compact"><span>Disponible</span><strong>{{ number_format($results['stock_summary']['available_units'], 0, ',', '.') }} uds</strong></article><article class="surface-card kpi-card kpi-compact"><span>Bloqueado / obsoleto</span><strong>{{ number_format($results['stock_summary']['blocked_units'] + $results['stock_summary']['obsolete_units'], 0, ',', '.') }} uds</strong></article><article class="surface-card kpi-card kpi-compact"><span>Ajustes manuales</span><strong>{{ $results['manual_adjustments'] }}</strong></article></section>
        <div class="traceability-content-grid">
            <section class="surface-card stock-table-shell compact-card"><div class="item-form-header"><div class="app-copy"><h2 class="ops-page-title page-title-compact">Rotacion</h2></div></div><div class="data-table-wrap"><table class="data-table table-compact"><thead><tr><th>SKU / articulo</th><th class="numeric-cell">Entradas</th><th class="numeric-cell">Salidas</th><th class="numeric-cell">Movimiento</th></tr></thead><tbody>@forelse ($results['rankings'] as $row)<tr><td><strong>{{ $row->sku }}</strong><small class="table-subline">{{ $row->description }}</small></td><td class="numeric-cell">{{ number_format($row->inbound_units, 0, ',', '.') }}</td><td class="numeric-cell">{{ number_format($row->outbound_units, 0, ',', '.') }}</td><td class="numeric-cell">{{ number_format($row->rotation_units, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="4">Sin movimiento en el periodo.</td></tr>@endforelse</tbody></table></div></section>
            <section class="surface-card stock-table-shell compact-card"><div class="item-form-header"><div class="app-copy"><h2 class="ops-page-title page-title-compact">Prevision explicable</h2></div></div><div class="traceability-event-list">@forelse ($results['forecasts'] as $entry)<article><strong>{{ $entry['item']->sku }} · {{ $entry['item']->description }}</strong><span>{{ $entry['forecast']['reason'] }}</span><span>Confianza: {{ $entry['forecast']['confidence'] }} · Metodo: {{ $entry['forecast']['method'] }}</span></article>@empty<p class="helper-text">Selecciona un articulo o genera movimiento para calcular previsiones.</p>@endforelse</div></section>
        </div>
        <section class="surface-card stock-table-shell compact-card"><div class="item-form-header"><div class="app-copy"><h2 class="ops-page-title page-title-compact">Articulos sin movimiento</h2></div></div><div class="data-table-wrap"><table class="data-table table-compact"><thead><tr><th>SKU</th><th>Articulo</th><th class="numeric-cell">Stock actual</th></tr></thead><tbody>@forelse ($results['without_movement'] as $item)<tr><td><strong>{{ $item->sku }}</strong></td><td>{{ $item->description }}</td><td class="numeric-cell">{{ number_format($item->current_units ?? 0, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="3">Todos los articulos seleccionados tienen movimiento.</td></tr>@endforelse</tbody></table></div></section>
    @else
        <article class="surface-card item-empty-state compact-card"><h3>Selecciona un cliente</h3><p>La analitica se calcula por cliente y periodo, nunca sobre todo el historico sin limite.</p></article>
    @endif
@endsection
